"""Train/evaluate ResNet18 transfer learning for UTKFace age-bin classification.

Initial code template for this file was generated by ChatGPT.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report, confusion_matrix
from torch.utils.data import DataLoader, TensorDataset, random_split

from model import create_resnet18_transfer_model
from utils import generate_age_bins, get_transforms, load_utkface_tensors

DEFAULT_MIN_AGE = 0
DEFAULT_MAX_AGE = 80
DEFAULT_BIN_SIZE = 3


def _to_float(value: float) -> float:
    """Convert metric values to plain Python floats for stable serialization."""
    return float(value)


def apply_bin_tolerance(y_true: list[int], y_pred: list[int], tolerance_bins: int) -> list[int]:
    """Treat near-bin predictions as correct by snapping them to ground truth within tolerance."""
    if tolerance_bins <= 0:
        return y_pred

    adjusted_preds: list[int] = []
    for truth, pred in zip(y_true, y_pred):
        if abs(pred - truth) <= tolerance_bins:
            adjusted_preds.append(truth)
        else:
            adjusted_preds.append(pred)
    return adjusted_preds


def evaluate_model(model, dataloader, device, class_names, tolerance_bins: int = 0):
    """Evaluate classifier and return loss + metrics for one dataloader."""
    criterion = nn.CrossEntropyLoss()

    model.eval()
    all_targets: list[int] = []
    all_preds: list[int] = []
    total_loss = 0.0

    with torch.no_grad():
        for batch_inputs, batch_labels in dataloader:
            batch_inputs = batch_inputs.to(device)
            batch_labels = batch_labels.to(device)

            outputs = model(batch_inputs)
            loss = criterion(outputs, batch_labels)
            total_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            all_targets.extend(batch_labels.cpu().numpy().tolist())
            all_preds.extend(preds.cpu().numpy().tolist())

    avg_loss = total_loss / len(dataloader)

    effective_preds = apply_bin_tolerance(all_targets, all_preds, tolerance_bins=tolerance_bins)

    report = classification_report(
        all_targets,
        effective_preds,
        target_names=class_names,
        labels=list(range(len(class_names))),
        output_dict=True,
        zero_division=0,
    )

    metrics = {
        "loss": _to_float(avg_loss),
        "accuracy": _to_float(report["accuracy"]),
        "macro_precision": _to_float(report["macro avg"]["precision"]),
        "macro_recall": _to_float(report["macro avg"]["recall"]),
        "macro_f1": _to_float(report["macro avg"]["f1-score"]),
        "weighted_precision": _to_float(report["weighted avg"]["precision"]),
        "weighted_recall": _to_float(report["weighted avg"]["recall"]),
        "weighted_f1": _to_float(report["weighted avg"]["f1-score"]),
        "y_true": all_targets,
        "y_pred": all_preds,
        "y_pred_effective": effective_preds,
        "tolerance_bins": tolerance_bins,
    }

    return metrics


def save_metrics_csv(history: list[dict[str, float]], output_csv_path: str | Path) -> None:
    """Save per-epoch metrics history as a CSV table."""
    fieldnames = [
        "epoch",
        "train_loss",
        "val_loss",
        "val_accuracy",
        "val_macro_precision",
        "val_macro_recall",
        "val_macro_f1",
        "val_weighted_precision",
        "val_weighted_recall",
        "val_weighted_f1",
    ]

    output_csv_path = Path(output_csv_path)
    output_csv_path.parent.mkdir(parents=True, exist_ok=True)

    with output_csv_path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(history)


def plot_training_curves(history: list[dict[str, float]], output_plot_path: str | Path) -> None:
    """Plot loss/accuracy/F1 validation curves across epochs."""
    output_plot_path = Path(output_plot_path)
    output_plot_path.parent.mkdir(parents=True, exist_ok=True)

    epochs = [row["epoch"] for row in history]

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    axes[0].plot(epochs, [row["train_loss"] for row in history], label="Train Loss")
    axes[0].plot(epochs, [row["val_loss"] for row in history], label="Val Loss")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].legend()

    axes[1].plot(epochs, [row["val_accuracy"] for row in history], label="Val Accuracy")
    axes[1].set_title("Validation Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].set_ylim(0, 1)
    axes[1].legend()

    axes[2].plot(epochs, [row["val_macro_f1"] for row in history], label="Val Macro F1")
    axes[2].plot(epochs, [row["val_weighted_f1"] for row in history], label="Val Weighted F1")
    axes[2].set_title("Validation F1")
    axes[2].set_xlabel("Epoch")
    axes[2].set_ylabel("F1 Score")
    axes[2].set_ylim(0, 1)
    axes[2].legend()

    fig.tight_layout()
    fig.savefig(output_plot_path, dpi=200)
    plt.close(fig)


def save_confusion_matrix(y_true, y_pred, class_names, output_path: str | Path, title: str) -> None:
    """Render and save a confusion matrix heatmap."""
    cm = confusion_matrix(y_true, y_pred, labels=list(range(len(class_names))))
    cm_normalized = cm.astype(np.float64) / cm.sum(axis=1, keepdims=True).clip(min=1)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(10, 8))
    heatmap = ax.imshow(cm_normalized, cmap="Blues", aspect="auto")
    ax.set_title(title)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("True")
    ax.set_xticks(range(len(class_names)))
    ax.set_yticks(range(len(class_names)))
    ax.set_xticklabels(class_names, rotation=90)
    ax.set_yticklabels(class_names)
    fig.colorbar(heatmap, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(output_path, dpi=200)
    plt.close(fig)


def print_metrics_table(metrics: dict[str, float], split_name: str) -> None:
    """Print a compact console table for key split metrics."""
    print(f"\n{split_name} Metrics")
    print("-" * 72)
    print(f"{'Metric':<28} {'Value':>10}")
    print("-" * 72)

    rows = [
        ("Accuracy", metrics["accuracy"]),
        ("Macro Precision", metrics["macro_precision"]),
        ("Macro Recall", metrics["macro_recall"]),
        ("Macro F1", metrics["macro_f1"]),
        ("Weighted Precision", metrics["weighted_precision"]),
        ("Weighted Recall", metrics["weighted_recall"]),
        ("Weighted F1", metrics["weighted_f1"]),
    ]

    for name, value in rows:
        print(f"{name:<28} {value:>10.4f}")


def build_dataloaders(
    utkface_root: str,
    class_names: list[str],
    min_age: int,
    max_age: int,
    age_bin_size: int,
    batch_size: int,
    val_split: float,
    test_split: float,
    seed: int,
) -> tuple[DataLoader, DataLoader, DataLoader]:
    """Build train/validation/test dataloaders with deterministic splitting."""
    train_transforms = get_transforms(train=True)
    eval_transforms = get_transforms(train=False)

    train_data, labels = load_utkface_tensors(
        utkface_root=utkface_root,
        class_names=class_names,
        image_transforms=train_transforms,
        min_age=min_age,
        max_age=max_age,
        bin_size=age_bin_size,
    )
    eval_data, _ = load_utkface_tensors(
        utkface_root=utkface_root,
        class_names=class_names,
        image_transforms=eval_transforms,
        min_age=min_age,
        max_age=max_age,
        bin_size=age_bin_size,
    )

    full_dataset_train = TensorDataset(train_data, labels)
    full_dataset_eval = TensorDataset(eval_data, labels)

    total_samples = len(full_dataset_train)
    test_size = int(total_samples * test_split)
    val_size = int(total_samples * val_split)
    train_size = total_samples - val_size - test_size

    if train_size <= 0:
        raise ValueError(
            "Dataset split sizes are invalid. Reduce val_split/test_split or provide more data."
        )
    if val_size <= 0:
        raise ValueError("val_split is too small for this dataset; it produced 0 validation samples.")
    if test_size <= 0:
        raise ValueError("test_split is too small for this dataset; it produced 0 test samples.")

    generator = torch.Generator().manual_seed(seed)
    train_subset_eval, val_subset_eval, test_subset_eval = random_split(
        full_dataset_eval,
        [train_size, val_size, test_size],
        generator=generator,
    )

    # Use the same indices for augmented training tensors.
    train_subset = torch.utils.data.Subset(full_dataset_train, train_subset_eval.indices)

    train_loader = DataLoader(train_subset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_subset_eval, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_subset_eval, batch_size=batch_size, shuffle=False)
    return train_loader, val_loader, test_loader


def train_model(
    utkface_root: str,
    class_names: list[str] | None = None,
    min_age: int = DEFAULT_MIN_AGE,
    max_age: int = DEFAULT_MAX_AGE,
    age_bin_size: int = DEFAULT_BIN_SIZE,
    batch_size: int = 4,
    epochs: int = 10,
    lr: float = 1e-3,
    model_path: str = "model_state.pth",
    val_split: float = 0.15,
    test_split: float = 0.15,
    seed: int = 42,
    metrics_dir: str = "artifacts/metrics",
    eval_only: bool = False,
    tolerance_bins: int = 0,
) -> str:
    """Train a transfer-learning ResNet18 classifier and save model + metric artifacts."""
    if tolerance_bins < 0:
        raise ValueError("tolerance_bins must be >= 0.")

    class_names = class_names or generate_age_bins(
        min_age=min_age,
        max_age=max_age,
        bin_size=age_bin_size,
    )

    train_loader, val_loader, test_loader = build_dataloaders(
        utkface_root=utkface_root,
        class_names=class_names,
        min_age=min_age,
        max_age=max_age,
        age_bin_size=age_bin_size,
        batch_size=batch_size,
        val_split=val_split,
        test_split=test_split,
        seed=seed,
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = create_resnet18_transfer_model(num_classes=len(class_names), feature_extract=True)
    model = model.to(device)

    history: list[dict[str, float]] = []
    if eval_only:
        checkpoint = torch.load(model_path, map_location=device)
        if "model_state_dict" not in checkpoint:
            raise ValueError(
                f"Checkpoint '{model_path}' does not contain 'model_state_dict'. Cannot run eval-only."
            )
        if "class_names" in checkpoint and checkpoint["class_names"] != class_names:
            print(
                "Warning: class_names in checkpoint differ from current CLI bin settings. "
                "Using checkpoint class_names for evaluation."
            )
            class_names = checkpoint["class_names"]
            model = create_resnet18_transfer_model(num_classes=len(class_names), feature_extract=True)
            model = model.to(device)
            train_loader, val_loader, test_loader = build_dataloaders(
                utkface_root=utkface_root,
                class_names=class_names,
                min_age=min_age,
                max_age=max_age,
                age_bin_size=age_bin_size,
                batch_size=batch_size,
                val_split=val_split,
                test_split=test_split,
                seed=seed,
            )

        model.load_state_dict(checkpoint["model_state_dict"])
        print(f"Loaded checkpoint from {model_path} for evaluation-only mode.")
    else:
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.fc.parameters(), lr=lr)

        best_val_acc = -1.0
        best_state_dict = None

        model.train()
        for epoch in range(epochs):
            running_loss = 0.0

            for batch_inputs, batch_labels in train_loader:
                batch_inputs = batch_inputs.to(device)
                batch_labels = batch_labels.to(device)

                optimizer.zero_grad()
                outputs = model(batch_inputs)
                loss = criterion(outputs, batch_labels)
                loss.backward()
                optimizer.step()

                running_loss += loss.item()

            avg_train_loss = running_loss / len(train_loader)

            val_metrics = evaluate_model(
                model,
                val_loader,
                device,
                class_names,
                tolerance_bins=tolerance_bins,
            )

            history_row = {
                "epoch": epoch + 1,
                "train_loss": _to_float(avg_train_loss),
                "val_loss": val_metrics["loss"],
                "val_accuracy": val_metrics["accuracy"],
                "val_macro_precision": val_metrics["macro_precision"],
                "val_macro_recall": val_metrics["macro_recall"],
                "val_macro_f1": val_metrics["macro_f1"],
                "val_weighted_precision": val_metrics["weighted_precision"],
                "val_weighted_recall": val_metrics["weighted_recall"],
                "val_weighted_f1": val_metrics["weighted_f1"],
            }
            history.append(history_row)

            print(
                f"Epoch {epoch + 1}/{epochs} | "
                f"Train Loss: {avg_train_loss:.4f} | "
                f"Val Loss: {val_metrics['loss']:.4f} | "
                f"Val Acc: {val_metrics['accuracy']:.4f} | "
                f"Val Macro F1: {val_metrics['macro_f1']:.4f}"
            )

            if val_metrics["accuracy"] > best_val_acc:
                best_val_acc = val_metrics["accuracy"]
                best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

            model.train()

        if best_state_dict is None:
            best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        model.load_state_dict(best_state_dict)

    final_val_metrics = evaluate_model(
        model,
        val_loader,
        device,
        class_names,
        tolerance_bins=tolerance_bins,
    )
    test_metrics = evaluate_model(
        model,
        test_loader,
        device,
        class_names,
        tolerance_bins=tolerance_bins,
    )

    metrics_dir_path = Path(metrics_dir)
    if history:
        save_metrics_csv(history, metrics_dir_path / "training_history.csv")
        plot_training_curves(history, metrics_dir_path / "training_curves.png")
    save_confusion_matrix(
        test_metrics["y_true"],
        test_metrics["y_pred_effective"],
        class_names,
        metrics_dir_path / "test_confusion_matrix.png",
        title=(
            "Normalized Confusion Matrix (Test, "
            f"tolerance={tolerance_bins} bin{'s' if tolerance_bins != 1 else ''})"
        ),
    )

    print_metrics_table(final_val_metrics, split_name="Validation")
    print_metrics_table(test_metrics, split_name="Test")

    if not eval_only:
        torch.save(
            {
                "model_state_dict": model.state_dict(),
                "class_names": class_names,
                "val_metrics": {
                    key: value
                    for key, value in final_val_metrics.items()
                    if key not in {"y_true", "y_pred", "y_pred_effective"}
                },
                "test_metrics": {
                    key: value
                    for key, value in test_metrics.items()
                    if key not in {"y_true", "y_pred", "y_pred_effective"}
                },
                "metrics_dir": str(metrics_dir_path),
            },
            model_path,
        )
        print(f"Model checkpoint saved to {model_path}")
    print(f"Metrics saved under: {metrics_dir_path}")
    return model_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train ResNet18 transfer-learning classifier")
    parser.add_argument(
        "--utkface-root",
        default="datasets/UTKFace",
        help="Directory containing prepared UTKFace images.",
    )
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--min-age", type=int, default=DEFAULT_MIN_AGE)
    parser.add_argument("--max-age", type=int, default=DEFAULT_MAX_AGE)
    parser.add_argument(
        "--age-bin-size",
        type=int,
        default=DEFAULT_BIN_SIZE,
        help="Width of each age category in years.",
    )
    parser.add_argument("--val-split", type=float, default=0.15)
    parser.add_argument("--test-split", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--metrics-dir",
        default="artifacts/metrics",
        help="Directory where CSV and plots are written.",
    )
    parser.add_argument(
        "--eval-only",
        action="store_true",
        help="Skip training and only evaluate a saved checkpoint on val/test splits.",
    )
    parser.add_argument(
        "--tolerance-bins",
        type=int,
        default=0,
        help=(
            "Treat predictions within +/- N neighboring age bins as correct for metrics. "
            "Use 1 to count left/right adjacent bins as correct."
        ),
    )
    parser.add_argument("--model-path", default="model_state.pth")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    train_model(
        utkface_root=args.utkface_root,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        min_age=args.min_age,
        max_age=args.max_age,
        age_bin_size=args.age_bin_size,
        val_split=args.val_split,
        test_split=args.test_split,
        seed=args.seed,
        metrics_dir=args.metrics_dir,
        eval_only=args.eval_only,
        tolerance_bins=args.tolerance_bins,
        model_path=args.model_path,
    )
